name: 'Kubigo Release Action'
description: 'Automatically create releases in Kubigo after successful builds'
author: 'Kubigo'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  api-key:
    description: 'Kubigo API Key (store in secrets)'
    required: true
  service:
    description: 'Service name or ID to deploy (e.g., "api-service", "frontend-app")'
    required: true
  images:
    description: 'Docker images to deploy (comma-separated or newline-separated for multiple containers)'
    required: true
  target:
    description: 'Target environment to deploy to (e.g., development, staging, production). If not specified, deploys to all targets.'
    required: false
  kubigo-url:
    description: 'Kubigo API URL (optional, defaults to https://api.kubigo.com)'
    required: false
    default: 'https://api.kubigo.com'
  triggered-by:
    description: 'Who/what triggered this release (optional, defaults to github-actions)'
    required: false
    default: 'github-actions'
  repository-url:
    description: 'Repository URL (optional, auto-detected, for audit/tracking only)'
    required: false
  branch:
    description: 'Git branch (optional, auto-detected, for audit/tracking only)'
    required: false
  commit-sha:
    description: 'Git commit SHA (optional, auto-detected, for audit/tracking only)'
    required: false

outputs:
  releases-created:
    description: 'Number of releases created'
  releases-auto-deployed:
    description: 'Number of releases auto-deployed'
  service-id:
    description: 'ID of the matched service'
  service-name:
    description: 'Name of the matched service'
  success:
    description: 'Whether the operation was successful'

runs:
  using: 'node20'
  main: 'dist/index.js'
