name: 'Kubigo Release Action'
description: 'Deploy container images to Kubigo environments'
author: 'Kubigo'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  api-key:
    description: 'Kubigo API Key (store in secrets)'
    required: true
  target-id:
    description: 'Target ID to deploy to (format: project/service/target, e.g., "my-team/api-service/production")'
    required: true
  images:
    description: 'Docker images to deploy (comma-separated or newline-separated for multiple containers)'
    required: true
  kubigo-url:
    description: 'Kubigo API URL (optional, defaults to https://app.kubigo.cloud)'
    required: false
    default: 'https://app.kubigo.cloud'
  triggered-by:
    description: 'Who/what triggered this release (optional, defaults to github-actions)'
    required: false
    default: 'github-actions'
  repository-url:
    description: 'Repository URL (optional, auto-detected, for audit/tracking only)'
    required: false
  branch:
    description: 'Git branch (optional, auto-detected, for audit/tracking only)'
    required: false
  commit-sha:
    description: 'Git commit SHA (optional, auto-detected, for audit/tracking only)'
    required: false

outputs:
  release-id:
    description: 'ID of the created release'
  release-status:
    description: 'Status of the release (pending, deployed, failed)'
  target-id:
    description: 'ID of the deployment target'
  service-id:
    description: 'ID of the service'
  success:
    description: 'Whether the operation was successful'

runs:
  using: 'node20'
  main: 'dist/index.js'
