name: Basic Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker Image
        run: |
          docker build -t myrepo/myapp:${{ github.sha }} .
          docker push myrepo/myapp:${{ github.sha }}
      
      - name: Create Release in Kubigo
        uses: kubigo/kubigo-release-action@v1
        with:
          api-url: ${{ secrets.KUBIGO_API_URL }}
          api-key: ${{ secrets.KUBIGO_API_KEY }}
          image-tag: myrepo/myapp:${{ github.sha }}
